# Generated by Django 5.2.17 on 2026-09-10 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0014_alter_dsocevent_rcvr_station_alter_dsocevent_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dsocEvent',
        ),
        migrations.DeleteModel(
            name='ETransferEvent',
        ),
        migrations.DeleteModel(
            name='gbtEvent',
        ),
        migrations.DeleteModel(
            name='uiEvent',
        ),
        migrations.AddField(
            model_name='observatoryevent',
            name='gbt_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
